[package]
name = "gresiq"
description = "GresIQ is a serverlessPostgresSQL client for on the smbCloud platform."
version = "0.1.0"
edition = "2024"
readme = "README.md"

[dependencies]
tokio = { workspace = true, features = ["full"] }
tokio-postgres = { workspace = true }
