[package]
name = "smbcloud-networking-account"
version = "0.3.23"
edition = "2024"

[dependencies]
reqwest = { workspace = true, features = ["json"] }
smbcloud-model = { workspace = true }
smbcloud-network = { workspace = true }
smbcloud-networking = { workspace = true }
