[package]
name = "smbcloud-networking-account-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
network = { workspace = true }
smbcloud-networking = { workspace = true }
smbcloud-model = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = "0.4.50"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_repr = { workspace = true }
thiserror = { workspace = true }
serde-wasm-bindgen = "=0.6.5"
